name: airletter
services:
  app:
    build:
      context: .
      dockerfile: docker/app/local/Dockerfile
    container_name: airletter_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      .env
    networks:
      default:

  worker:
    build:
      context: .
      dockerfile: docker/app/local/Dockerfile
    container_name: goquicksend_worker
    command: ["air", "-c", ".air.worker.toml"]
    volumes:
      - .:/app
    env_file:
      .env
    depends_on:
      - db
      - redis
    networks:
      default:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: airletter_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: unless-stopped
    networks:
      default:

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: airletter_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      default:

  redis:
    image: redis:8.4.0
    container_name: airletter_redis
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      default:

  asynqmon:
    image: hibiken/asynqmon:0.7.2
    container_name: airletter_asynqmon
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "8090:8080"
    command: ["--redis-url=${REDIS_URL}"]
    depends_on:
      - redis
    networks:
      default:

networks:
  default:
    name: airletter_network
    external: true

volumes:
  redis_data:
  postgres_data:
