BEGIN;

DROP TABLE IF EXISTS attachments;
DROP TABLE IF EXISTS recipients;
DROP TABLE IF EXISTS campaigns;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS users;

COMMIT;
